apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  labels:
    app: {{ .Values.app_name }}
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision | quote }}
    umbrella: {{ .Values.umbrella_name }}
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
  maxReplicas: {{ .Values.hpa.max }}
  minReplicas: {{ .Values.hpa.min }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: {{ .Values.hpa.kind }}
    name: {{ .Values.app_name }}
  metrics:
{{- if .Values.hpa.metrics }}
{{ toYaml .Values.hpa.metrics | indent 4 }}
{{- end }}