apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- range $key, $val := .Values.service.additional_annotations }}
    {{ $key }}: {{ $val | quote}}
    {{- end }}
  labels:
    app: {{ .Values.app_name }}
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision | quote }}
    umbrella: {{ .Values.umbrella_name }}
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
{{- with .Values.service }}
  type: {{ .type }}
  sessionAffinity: {{ .session_affinity }}
  {{ if .loadBalancerSourceRanges }}
  loadBalancerSourceRanges: 
    {{- range .loadBalancerSourceRanges }}
    - {{ . | title | quote }}
    {{- end }}
  {{ end }}
{{- end }}
{{- with .Values.service }}
  ports:
  - name: {{ .name }}
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .container_port }}
{{- end }}

  selector:
    app: {{ .Values.app_name }}
