apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.app_name }}
    release: {{ .Release.Name }}
    revision: {{ .Release.Revision | quote }}
    umbrella: {{ .Values.umbrella_name }}
  name: {{ .Values.app_name }}
  namespace: {{ .Values.namespace }}
spec:
{{- with .Values.service }}
  type: {{ .type }}
  sessionAffinity: {{ .session_affinity }}
{{- end }}
{{- with .Values.service }}
  ports:
  - name: http
    port: {{ .port }}
    protocol: TCP
    targetPort: {{ .container_port }}
{{- end }}

  selector:
    app: {{ .Values.app_name }}
