---
name: cms.api.campaign
kind: service
tasks:
  - name: build
    command:
      - git diff-tree --name-only -r HEAD
      - echo "build step"
      - chmod +x coverage-tests.sh
      - ./coverage-tests.sh
    timeout: 600m

  - name: codescan
    kind: Sonarqube-Dotnet
    project: cms.api.campaign
    solution: ./CMS.API.Campaign.sln
    analysisOptions:
      - key: sonar.cs.opencover.reportsPaths
        value: "./TestResult/TR-*.xml"
      - key: sonar.coverage.exclusions
        value: "**Test*.cs, **Startup.cs, **Program.cs"
        
  - name: artifacts
    kind: Docker
    images:
      - name: cms-campaignapi
        path: "CMS.API.Campaign.WebApi"  
        
  - name: helmChart
    kind: helmpush
    charts:
      - name: cms-campaignapi
        path: ./charts/cms-campaignapi
        image: cms-campaignapi      