umbrella_name: cms
app_name: cms-campaignapi
namespace: cms

deployment:
  progress_deadline_seconds: 600
  replicas: 1
  image:
    pull_policy: IfNotPresent
    pull_secret: jfrog-authenticate
    #pull_secret: hs-reg-iherb-net-svc-k8sdeploy-hs
  http:
    port: 80
    container_port: 80
  liveness:
    failure_threshold: 3
    path: /api/HealthCheck
    initial_delay_seconds: 60
    period_seconds: 60
    success_threshold: 1
    timeout_seconds: 1
  readiness:
    failure_threshold: 3
    path: /api/HealthCheck
    initial_delay_seconds: 60
    period_seconds: 60
    success_threshold: 1
    timeout_seconds: 1
  resources:
    limits:
      cpu: 800m
      memory: 1000Mi
    requests:
      cpu: 400m
      memory: 800Mi

hpa:
  min: 2
  max: 4
  kind: Deployment
  cpu_utilization: 80
  
service:
  type: ClusterIP
  name: http
  port: 80
  container_port: 80
  session_affinity: None
  
ingress:
  create: true
  rules:
    - host: campaign.internal.iherbtest.io
      backends:
        - path: /
  secrets:
    - host: campaign.internal.iherbtest.io
      secret: 

monitor:
  create: true

prometheusrule:
  create: true
  rules:
    - alert: EndpointResponseTime
      annotations:
        summary: ""
        message: calculate response time is above 5s
        runbook_url: ""
        dashboard_url: ""
      expr: >
        min(avg_over_time(application_httprequests_transactions_per_endpoint{app="CMS.API.Campaign.WebApi",quantile="0.99"}[1m]))
        > 5
      for: 5m
      labels:
        severity: warning
        opsgenie_priority: P5

secret:
  create: true
  data:
    Secret__Test: SecretTest
  
configmap:
  data:
    RedisConfig__ConnectionString: cms-redis-slave:6379